apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 3
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - image: wuwun9/go-app:1.0
        name: go-psite
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 3000
